aoscx_l2_interface: Fix E122: continuation line missing indentation or outdented
ERROR: plugins/modules/aoscx_l2_interface.py:427:20: E122: continuation line missing indentation or outdented

Signed-off-by: Alexis La Goutte <alexis.lagoutte@gmail.com>