aoscx_qos_cx: Fix E203: whitespace before ',' /  E231: missing whitespace after ','
ERROR: plugins/modules/aoscx_qos_cos.py:95:41: E203: whitespace before ','
ERROR: plugins/modules/aoscx_qos_cos.py:95:42: E231: missing whitespace after ','

Signed-off-by: Alexis La Goutte <alexis.lagoutte@gmail.com>