aoscx(module_utils): Fix  invalid-ansiblemodule-schema/invalid-deprecated-version/deprecation-collection-missing
Issue found by ansible-test sanity (validate-modules)

ERROR: plugins/modules/aoscx_config.py:0:0: invalid-ansiblemodule-schema: AnsibleModule.argument_spec.provider.removed_in_version: expected str for dictionary value @ data['argument_spec']['provider']['removed_in_version']. Got 2.14
ERROR: plugins/modules/aoscx_config.py:0:0: invalid-deprecated-version: Argument 'provider' in argument_spec has an invalid removed_in_version number 2.14: invalid semantic version '2.14'
ERROR: plugins/modules/aoscx_facts.py:0:0: invalid-ansiblemodule-schema: AnsibleModule.argument_spec.provider.removed_in_version: expected str for dictionary value @ data['argument_spec']['provider']['removed_in_version']. Got 2.14
ERROR: plugins/modules/aoscx_facts.py:0:0: invalid-deprecated-version: Argument 'provider' in argument_spec has an invalid removed_in_version number 2.14: invalid semantic version '2.14'
ERROR: plugins/modules/aoscx_config.py:0:0: deprecation-collection-missing: AnsibleModule.argument_spec.provider: If removed_in_version or removed_at_date is specified, removed_from_collection must be specified as well for dictionary value @ data['argument_spec']['provider']. Got {'type': 'dict', 'options': {'host': {}, 'port': {'type': 'int'}, 'username': {'fallback': (<function env_fallback at 0x7f4f58fbb280>, ['ANSIBLE_NET_USERNAME'])}, 'password': {'fallback': (<function env_fallback at 0x7f4f58fbb280>, ['ANSIBLE_NET_PASSWORD']), 'no_log': True}, 'ssh_keyfile': {'fallback': (<function env_fallback at 0x7f4f58fbb280>, ['ANSIBLE_NET_SSH_KEYFILE']), 'type': 'path'}, 'authorize': {'fallback': (<function env_fallback at 0x7f4f58fbb280>, ['ANSIBLE_NET_AUTHORIZE']), 'typ...
Signed-off-by: Alexis La Goutte <alexis.lagoutte@gmail.com>