acl(aoscx): fix DOCUMENTATION (ansible-doc...)
Fix

ERROR! module arubanetworks.aoscx.aoscx_acl missing documentation (or could not parse documentation): arubanetworks.aoscx.aoscx_acl did not contain a DOCUMENTATION attribute (/root/ansible_collections/arubanetworks/aoscx/plugins/modules/aoscx_acl.py). Unable to parse documentation in python file '/root/ansible_collections/arubanetworks/aoscx/plugins/modules/aoscx_acl.py': while scanning for the next token
found character that cannot start any token
  in "<unicode string>", line 97, column 9. while scanning for the next token
found character that cannot start any token
  in "<unicode string>", line 97, column 9

and

ERROR: plugins/modules/aoscx_acl.py:114:9: error: DOCUMENTATION: syntax error: found character '`' that cannot start any token (syntax)
ERROR: plugins/modules/aoscx_acl.py:114:9: unparsable-with-libyaml: while scanning for the next token - found character that cannot start any token
(cherry picked from commit 243c4b8378d92a3303d65ec3ce5fe1db90231d88)